services:
  ai-audio-training:
    build: .
    container_name: ai_audio_training
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - .:/app
    command: ["./entrypoint.sh"]
